services:
  usuarioservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuarioservice
    environment:
      # Variables necesarias para conectarse a Oracle Cloud usando el Wallet
      SPRING_DATASOURCE_URL: "jdbc:oracle:thin:@fullstack3_low?TNS_ADMIN=/app/wallet"
      SPRING_DATASOURCE_USERNAME: "USUARIOSERVICE_USR"
      SPRING_DATASOURCE_PASSWORD: "Fs3Destilado"
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "oracle.jdbc.driver.OracleDriver"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: 10
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    ports:
      - "8080:8080"

    volumes:
      # Montar el Wallet para que tu aplicación pueda acceder a él
      - ./wallet:/app/wallet

